server:
  port: 8082
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /hclg


spring:
  datasource:
    url: jdbc:mysql://192.168.100.54/houchang_program
    username: houchangprogram
    password: KaikeB80826
    type: com.alibaba.druid.pool.DruidDataSource
      # 连接池配置
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
    #配置别名
  type-aliases-package: com.hclg.hc_confirm_order.pojo

